version: '2'

volumes:
  node_modules:

services:
  gatsby:
    container_name: gatsby
    build:
      context: .
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
      # mount empty node_modules exclude the node_modules on host system from mounting into the container
      - node_modules:/home/node/app/node_modules
    ports:
      - '8000:8000'
    command: 'yarn devDocker'
